### PR TITLE
Fix schema builder to copy extensionDefinitions

### LINKED ISSUE #3427: Copying of extensionDefinitions when generating a new builder
**Describe the bug**
The `graphql.schema.GraphQLSchema#newSchema(graphql.schema.GraphQLSchema)` method does not copy the `graphql.schema.GraphQLSchema.Builder#extensionDefinitions` when generating a new builder from the existing `GraphQLSchema`. Is there a reason for this? Do I need to redefine the extensions when generating a new builder?

An easy fix would probably be:
```java
return new Builder()
        ...
        .extensionDefinitions(existingSchema.getExtensionDefinitions())
        ...
```

### PR DESCRIPTION
**Pull request by dondonz**
Fixes #3427 

Adds a forgotten builder method

### CODE REVIEW

File: src/main/java/graphql/schema/GraphQLSchema.java [hunk 1]
```diff
@@ -71,7 +71,7 @@ public class GraphQLSchema {
     private final ImmutableMap<String, ImmutableList<String>> interfaceNameToObjectTypeNames;
 
     /*
-     * This constructs partial GraphQL schema object which has has the schema (query / mutation / subscription) trees
+     * This constructs partial GraphQL schema object which has the schema (query / mutation / subscription) trees
```
Comment (dondonz) [inline src/main/java/graphql/schema/GraphQLSchema.java:74]: IntelliJ suggested these grammar edits, unrelated to builder fix

File: src/main/java/graphql/schema/GraphQLSchema.java [hunk 2]
```diff
@@ -641,6 +641,7 @@ public static Builder newSchema(GraphQLSchema existingSchema) {
                 .query(existingSchema.getQueryType())
                 .mutation(existingSchema.getMutationType())
                 .subscription(existingSchema.getSubscriptionType())
+                .extensionDefinitions(existingSchema.getExtensionDefinitions())
```
Comment (dondonz) [inline src/main/java/graphql/schema/GraphQLSchema.java:644]: This is the key change - add to builder

**Review by bbakerman — APPROVED** [review]
