### PR TITLE
684 batched es does not handle exceptions

### LINKED ISSUE #684: BatchedExecutionStrategy doesn't properly handle exceptions when fetching non-null fields
BatchedExecutionStrategy doesn't properly handle null values for non-nullable fields if null value is the result of an exception during data fetcher execution.

The following method should run to completion and print out an error list, but instead throws an exception during execution:
```java
public void testBatchExceptions() {
    GraphQLSchema schema = GraphQLSchema.newSchema()
        .query(newObject()
            .name("Query")
            .field(newFieldDefinition()
                .name("user")
                .type(newObject()
                    .name("User")
                    .field(newFieldDefinition()
                        .name("id")
                        .type(new GraphQLNonNull(Scalars.GraphQLInt))
                        .dataFetcher(e -> {
                            throw new RuntimeException("Hello");
                        })
                    )
                    .build())
                .dataFetcher(environment -> {
                    Map<String, Object> user = new HashMap<>();
                    user.put("id", 1);
                    return user;
                })
                .build())
            .build())
        .build();

    GraphQL graphQL = GraphQL.newGraphQL(schema)
        .queryExecutionStrategy(new BatchedExecutionStrategy())
        .build();

    ExecutionInput executionInput = ExecutionInput.newExecutionInput()
        .query("query { user { id } }")
        .build();

    ExecutionResult result = graphQL.execute(executionInput);
    System.out.println(result.getErrors());
}
```
```
graphql.GraphQLException: Found null value for non-null type with parent: 'User' for fields: [Field{name='id', alias='null', arguments=[], directives=[], selectionSet=null}]

	at graphql.execution.batched.BatchedExecutionStrategy.handleNonNullType(BatchedExecutionStrategy.java:254)
	at graphql.execution.batched.BatchedExecutionStrategy.completeValues(BatchedExecutionStrategy.java:174)
	at graphql.execution.batched.BatchedExecutionStrategy.lambda$resolveField$2(BatchedExecutionStrategy.java:163)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at graphql.execution.batched.BatchedExecutionStrategy.resolveField(BatchedExecutionStrategy.java:158)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.lambda$executeImpl$1(BatchedExecutionStrategy.java:136)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.execute(BatchedExecutionStrategy.java:90)
	at graphql.execution.Execution.executeOperation(Execution.java:112)
	at graphql.execution.Execution.execute(Execution.java:65)
	at graphql.GraphQL.execute(GraphQL.java:466)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:414)
	at graphql.GraphQL.executeAsync(GraphQL.java:392)
	at graphql.GraphQL.execute(GraphQL.java:329)
```
Using `AsyncExecutionStrategy` or removing non-null from User.id field works as it should.

### PR DESCRIPTION
**Pull request by bbakerman**
This technically fixes #684 but it is still not spec compliant re: 

http://facebook.github.io/graphql/#sec-Errors-and-Non-Nullability

But this is setting us up I think

### CODE REVIEW

File: src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java [hunk 1]
```diff
@@ -420,53 +465,6 @@ private boolean isObject(GraphQLType type) {
                 type instanceof GraphQLUnionType;
     }
```
Comment (bbakerman) [inline src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java]: The following is moved upwards near it call site

File: src/main/java/graphql/execution/batched/FetchedValues.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    private final List<FetchedValue> fetchedValues;
+    private final ExecutionTypeInfo executionTypeInfo;
+    private final ExecutionPath path;
+
+    public FetchedValues(List<FetchedValue> fetchedValues, ExecutionTypeInfo executionTypeInfo, ExecutionPath path) {
+        this.fetchedValues = fetchedValues;
+        this.executionTypeInfo = executionTypeInfo;
+        this.path = path;
+    }
+
```
Comment (bbakerman) [inline src/main/java/graphql/execution/batched/FetchedValues.java]: A list but with extra info
