### PR TITLE
Ensure NormalizedQueryTreeFactory handles mutations and subscriptions

### LINKED ISSUE #2117: DataFetchingEnvironment.getSelectionSet().getFields() is broken from Mutations after upgrade to graphql-java 16
**Describe the bug**
Trying to invoke `dataFetchingEnvironment.getSelectionSet().getFields()` from a Mutation results in `graphql.AssertException: no field with name mutationFieldName found in object Query` exception being thrown out.

This seems be caused by https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/normalized/NormalizedQueryTreeFactory.java#L55 that assume that root is always a Query.

This worked fine in graphql-java 15, and is broken after upgrade to graphql-java 16.

**To Reproduce**
From a DataFetcher that's registered to resolve a Mutation field invoke something like below:

```
DataFetchingFieldSelectionSet selectionSet = environment.getSelectionSet();
if (selectionSet.getFields().stream().allMatch(field -> SUPPORTED_FIELDS.contains(field.getName()))) { return "xyz"; }
```

### PR DESCRIPTION
**Pull request by austinarbor**
Credit to @skevy for original fix here https://github.com/graphql-java/graphql-java/pull/2126 but it seems like the PR has stalled on the assertion error

Creating new PR here with suggested assertion changes

Fixes #2117

### CODE REVIEW

File: src/main/java/graphql/normalized/NormalizedQueryTreeFactory.java [hunk 1]
```diff
@@ -1,14 +1,12 @@
...
 
+import graphql.Assert;
 import graphql.Internal;
 import graphql.execution.MergedField;
-import graphql.language.Document;
-import graphql.language.Field;
-import graphql.language.FragmentDefinition;
-import graphql.language.NodeUtil;
-import graphql.language.OperationDefinition;
+import graphql.language.*;
```
Comment (artem-ag) [inline src/main/java/graphql/normalized/NormalizedQueryTreeFactory.java:6]: Revert a change for wildcard import?

Comment (austinarbor) [reply src/main/java/graphql/normalized/NormalizedQueryTreeFactory.java]: done

**Comment by skevy** [comment]
Sorry about the stall. Thank you for picking it  up and fixing it!
