### PR TITLE
Fix #882, variable input type mismatch throws AssertException

### LINKED ISSUE #882: Variable input type mismatch throws an AssertException
## Issue
If a GraphQL variable refers to a non-null type that isn't defined in the schema, we raise an `AssertException` instead of a validation error.

## Steps to reproduce
The test below showcases the issue by attempting to validate a query with a variable that has an unknown type.

```groovy
def '5.7.3 Variables Are Input Types - non-null unknown type'() {
        def query = """
query madDog(\$dogCommand: UnknownType!){
    dog {
        doesKnowCommand(dogCommand: \$dogCommand)
    }
}"""
        when:
        def validationErrors = validate(query)

        then:
        !validationErrors.empty
        validationErrors.size() == 1
        validationErrors.get(0).getValidationErrorType() == ValidationErrorType.UnknownType
    }
```
will throw 

```
graphql.AssertException: wrappedType can't be null

	at graphql.Assert.assertNotNull(Assert.java:12)
	at graphql.schema.GraphQLNonNull.<init>(GraphQLNonNull.java:34)
	at graphql.execution.TypeFromAST.getTypeFromAST(TypeFromAST.java:22)
	at graphql.validation.TraversalContext.enterImpl(TraversalContext.java:141)
	at graphql.validation.TraversalContext.enter(TraversalContext.java:78)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:58)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:33)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:36)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:36)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:28)
	at graphql.validation.Validator.validateDocument(Validator.java:40)
	at graphql.validation.SpecValidationBase.validate(SpecValidationBase.groovy:18)
	at graphql.validation.SpecValidation573Test.5.7.3 Variables Are Input Types - non-null unknown type(SpecValidation573Test.groovy:49)
```

## Expected behavior

A validation error should be raised instead, similarly to what `graphql-js` does.
Here is what graphql-js returns:
```json
{
  "errors": [
    {
      "message": "Unknown type \"UnknownType\".",
      "locations": [
        {
          "line": 1,
          "column": 52
        }
      ]
    }
  ]
}```

### PR DESCRIPTION
**Pull request by tinnou**
### Description

Added a null check in `getTypeFromAST`, similarly to what [graphql-js does](https://github.com/graphql/graphql-js/blob/7e147a8dd60496505cd5d491fb7126b2319095c9/src/utilities/typeFromAST.js#L49):
They return `void` (undefined in js) or the type itself.
```javascript
export function typeFromAST(schema, typeNode) {
  /* eslint-enable no-redeclare */
  let innerType;
  if (typeNode.kind === Kind.LIST_TYPE) {
    innerType = typeFromAST(schema, typeNode.type);
    return innerType && GraphQLList(innerType);
  }
  if (typeNode.kind === Kind.NON_NULL_TYPE) {
    innerType = typeFromAST(schema, typeNode.type);
    return innerType && GraphQLNonNull(innerType);
  }
  if (typeNode.kind === Kind.NAMED_TYPE) {
    return schema.getType(typeNode.name.value);
  }
  /* istanbul ignore next */
  throw new Error(`Unexpected type kind: ${(typeNode.kind: empty)}.`);
}
```

### Testing
Added unit tests to cover this issue + bonus spec cases we missed earlier.

### CODE REVIEW

File: src/test/groovy/graphql/validation/SpecValidation573Test.groovy [hunk 1]
```diff
@@ -0,0 +1,72 @@
+package graphql.validation
+/**
+ * validation examples used in the spec in given section
+ * http://facebook.github.io/graphql/#sec-Validation
+ *
+ */
+class SpecValidation573Test extends SpecValidationBase {
+
+    def '5.7.3 Variables Are Input Types - type mismatch (must be non-null)'() {
+        def query = """
```
Comment (bbakerman) [inline src/test/groovy/graphql/validation/SpecValidation573Test.groovy]: If you want to use $ in a groovy multi line string, then just use ''' quotes instead.  No need for quoting the \$

Comment (tinnou) [reply src/test/groovy/graphql/validation/SpecValidation573Test.groovy]: oh neat I didn't know you could do that! Thanks for the merge by the way.
