### PR TITLE
Resolve TypeReferences in schema applied directives

### LINKED ISSUE #3053: TypeReferences not resolved in schema applied directives
**Describe the bug**
If an applied directive on the schema itself has a type reference, it stays unresolved.

**To Reproduce**
```java
@Test
public void testRef() {
        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(newObject()
                        .name("query")
                        .field(echo -> echo
                                .name("echo")
                                .type(Scalars.GraphQLString)))
                .additionalDirective(newDirective()
                        .name("cache")
                        .argument(enabled -> enabled
                                .name("enabled")
                                .type(Scalars.GraphQLBoolean))
                        .build())
                .withSchemaAppliedDirectives(GraphQLAppliedDirective.newDirective()
                        .name("cache")
                        .argument(enabled -> enabled
                                .name("enabled")
                                .type(GraphQLTypeReference.typeRef(Scalars.GraphQLBoolean.getName()))
                                .valueLiteral(new BooleanValue(true)))
                        .build())
                .build();
        assertFalse(schema.getSchemaAppliedDirective("cache").getArgument("enabled").getType() instanceof GraphQLTypeReference);
}
```

### PR DESCRIPTION
**Pull request by kaqqao**
Fixes #3053

### CODE REVIEW

**Comment by andimarek** [comment]
Thanks for raising this PR inlcuding test ... I will need to have a deeper look regarding the actual fix if that is the best way, because I think it should have been handled.

**Comment by kaqqao** [comment]
The traversal starts from the types and directive _definitions_, so the schema _applied_ directives get skipped.
Funnily enough, I remember being the one that added directives to this traversal years ago, so it only made sense I add the applied directives as well  now that they're a thing :)

File: src/main/java/graphql/schema/impl/SchemaUtil.java [hunk 1]
```diff
@@ -100,6 +100,7 @@ public static void replaceTypeReferences(GraphQLSchema schema) {
         final Map<String, GraphQLNamedType> typeMap = schema.getTypeMap();
         List<GraphQLSchemaElement> roots = new ArrayList<>(typeMap.values());
         roots.addAll(schema.getDirectives());
+        roots.addAll(schema.getSchemaAppliedDirectives());
```
Comment (bbakerman) [inline src/main/java/graphql/schema/impl/SchemaUtil.java:103]: This makes sense to me @andimarek - these objects are not in the schema (eg linked by other objects) - they are root level objects

**Review by bbakerman — APPROVED** [review]
