### PR TITLE
Fixes #763 QueryTraversal problem

### LINKED ISSUE #763: QueryTraversal doesn't work with Union types and __typename
Hi Guys,

I think i might have found a bug, it seems like the QueryTraversal class doesn't work with union types:

`java.lang.ClassCastException: graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLFieldsContainer
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:98)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:165)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:100)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:165)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:100)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:165)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:100)
	at graphql.analysis.QueryTraversal.visitPreOrder(QueryTraversal.java:64)
	at graphql.analysis.QueryTraversal.reducePreOrder(QueryTraversal.java:89)
	at graphql.analysis.MaxQueryDepthInstrumentation.lambda$beginValidation$1(MaxQueryDepthInstrumentation.java:31)`

This is with the 4.2 release but it looks like the QueryTraversal class hasn't changed in 5.0 yet. Will take a look and see if i can work out a patch.

-David

### PR DESCRIPTION
**Pull request by bbakerman**
See #763

### CODE REVIEW

File: src/test/groovy/graphql/analysis/QueryTraversalTest.groovy [hunk 1]
```diff
@@ -582,7 +581,6 @@ class QueryTraversalTest extends Specification {
                 subFoo: String  
             }
         """)
-        def visitor = Mock(QueryVisitor)
```
Comment (bbakerman) [inline src/test/groovy/graphql/analysis/QueryTraversalTest.groovy]: never used according to idea

File: src/main/java/graphql/introspection/Introspection.java [hunk 2]
```diff
@@ -461,11 +463,42 @@ private static String print(Object value, GraphQLInputType type) {
...
-                        .name("dummySchema")
+                        .name("IntrospectionQuery")
                         .field(SchemaMetaFieldDef)
                         .field(TypeMetaFieldDef)
                         .field(TypeNameMetaFieldDef)
                         .build())
                 .build();
     }
+
+    /**
```
Comment (bbakerman) [inline src/main/java/graphql/introspection/Introspection.java]: This was used in at least 2 spots (again according to IDEA) so I moved it into a common place with better common logic and type handling
