### PR TITLE
Fix double variable coercion in QueryTraverser

### LINKED ISSUE #2819: regression in GraphQLScalarType Coercing parseValue in 18.1
**Describe the bug**

I just hit a bug in production when deploying an upgrade from 18.0 to 18.1 that I think relates to some of the work in resolving https://github.com/graphql-java/graphql-java/issues/2811

I noticed the following in my production logs 

```
...
Caused by: graphql.schema.CoercingParseValueException: Variable 'memberDues' has an invalid value: Failed to parse input value 2022-05-16T19:52:37Z as ZonedDateTime
...

Caused by: java.lang.IllegalArgumentException: Unexpected input type: class java.time.ZonedDateTimeat com.meetup.graphql.wiring.CustomScalars.parseDateTimeValue(CustomScalars.java:38)at com.meetup.graphql.wiring.CustomScalars$1.parseValue(CustomScalars.java:71)at com.meetup.graphql.wiring.CustomScalars$1.parseValue(CustomScalars.java:63)at graphql.execution.ValuesResolver.externalValueToInternalValueForScalar(ValuesResolver.java:578)at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:510)at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:498)at graphql.execution.ValuesResolver.externalValueToInternalValueForObject(ValuesResolver.java:565)at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:517)at graphql.execution.ValuesResolver.externalValueToInternalValueForObject(ValuesResolver.java:565)at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:517)at graphql.execution.ValuesResolver.externalValueToInternalValue(ValuesResolver.java:498)at graphql.execution.ValuesResolver.externalValueToInternalValueForVariables(ValuesResolver.java:410)
```

note that the string `2022-05-16T19:52:37Z` is actually parsable as ZonedDateTime however I believe the issue is previously `parseValue` was receiving either a String or a StringValue and after this upgrade it started receiving the value that I was attempting to coerce it into, in this case a ZonedDateTime

is this new expected behavior or was this previous expected behavior that was underspecified until now?

Here's an abbreviated version of a custom scaler for parsing out ZonedDateTime values which is roughly based on the [docs](https://www.graphql-java.com/documentation/scalars/#example-implementation)

```java
  static ZonedDateTime parseDateTimeValue(Object input) {
    try {
      if (input instanceof StringValue) {
        return ZonedDateTime.parse(((StringValue) input).getValue());
      } else if (input instanceof String) {
        return ZonedDateTime.parse((String) input);
      } else throw new IllegalArgumentException("Unexpected input type: " + input.getClass()); <-- change in behavior causes this line to get evaluated
    } catch (Exception e) {
      throw new CoercingParseValueException(
          "Failed to parse input value " + input + " as ZonedDateTime", e);
    }
  }
  
public static final GraphQLScalarType DateTime =
      GraphQLScalarType.newScalar()
          .name("DateTime")
          .description("A custom scalar that handles timestamps")
          .coercing(
              new Coercing<ZonedDateTime, String>() {
                @Override
                public String serialize(Object dataFetcherResult) {
                  return // doesnt matter
                }

                @Override
                public ZonedDateTime parseValue(Object input) {
                  return parseDateTimeValue(input);
                }

                @Override
                public ZonedDateTime parseLiteral(Object input) {
                  return // doesnt matter
                }
              })
          .build();
```

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.

see above

### PR DESCRIPTION
**Pull request by dondonz**
This PR fixes double variable coercion in `QueryTraverser` and classes using traversal such as `MaxQueryComplexityInstrumentation`, `MaxQueryDepthInstrumentation`, and `FieldValidationSupport`. Fixes #2819.

## The double coercion problem
Previously, raw and coerced variables were represented as plain maps `Map<String, Object>`. Using the same type made it hard to distinguish raw from coerced variables and in some places, such as `MaxQueryDepthInstrumentation`, we unintentionally coerced variables twice. The double coercion was there for some time (e.g. #2458), but became a problem in v18.1 (see #2819)

```
Caused by: graphql.schema.CoercingParseValueException: Variable 'memberDues' has an invalid value: Failed to parse input value 2022-05-16T19:52:37Z as ZonedDateTime

Caused by: java.lang.IllegalArgumentException: Unexpected input type: class java.time.ZonedDateTime at com.meetup.graphql.wiring.CustomScalars.parseDateTimeValue(CustomScalars.java:38) ...
```

The `ZonedDateTime` custom scalar parser in the #2819 example accepts `String` and `StringValue`, but not itself, causing a `IllegalArgumentException` during the second coercion.

## The fix
This PR adds a `QueryTraverser` that handles already coerced variables, thus avoiding the problematic second coercion.

In most cases, when a new `QueryTraverser` is instantiated, the variables have already been coerced. Following #2773, traversal will usually take place after the `ExecutionContext` is instantiated.

### CODE REVIEW

File: src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java [hunk 1]
```diff
@@ -147,7 +147,7 @@ QueryTraverser newQueryTraverser(ExecutionContext executionContext) {
                 .schema(executionContext.getGraphQLSchema())
                 .document(executionContext.getDocument())
                 .operationName(executionContext.getExecutionInput().getOperationName())
-                .variables(executionContext.getVariables())
+                .coercedVariables(executionContext.getCoercedVariables())
```
Comment (bbakerman) [inline src/main/java/graphql/analysis/MaxQueryComplexityInstrumentation.java:150]: love it!

File: src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java [hunk 2]
```diff
@@ -84,7 +84,7 @@ QueryTraverser newQueryTraverser(ExecutionContext executionContext) {
                 .schema(executionContext.getGraphQLSchema())
                 .document(executionContext.getDocument())
                 .operationName(executionContext.getExecutionInput().getOperationName())
-                .variables(executionContext.getVariables())
+                .coercedVariables(executionContext.getCoercedVariables())
```
Comment (bbakerman) [inline src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java:87]: nice

File: src/main/java/graphql/analysis/QueryTraverser.java [hunk 3]
```diff
@@ -51,32 +51,38 @@ public class QueryTraverser {
     private QueryTraverser(GraphQLSchema schema,
                            Document document,
                            String operation,
-                           Map<String, Object> variables) {
-        assertNotNull(document, () -> "document can't be null");
+                           CoercedVariables coercedVariables) {
+        this.schema = schema;
```
Comment (bbakerman) [inline src/main/java/graphql/analysis/QueryTraverser.java:55]: did you get rid of `assertNotNull(document, () -> "document can't be null");` accidentilly here??

File: src/main/java/graphql/analysis/QueryTraverser.java [hunk 4]
```diff
@@ -51,32 +51,38 @@ public class QueryTraverser {
...
+                           Document document,
+                           String operation,
+                           RawVariables rawVariables) {
+        this.schema = schema;
+        NodeUtil.GetOperationResult getOperationResult = NodeUtil.getOperation(document, operation);
+        List<VariableDefinition> variableDefinitions = getOperationResult.operationDefinition.getVariableDefinitions();
+        this.fragmentsByName = getOperationResult.fragmentsByName;
+        this.roots = singletonList(getOperationResult.operationDefinition);
+        this.rootParentType = getRootTypeFromOperation(getOperationResult.operationDefinition);
+        this.coercedVariables = new ValuesResolver().coerceVariableValues(schema, variableDefinitions, rawVariables);
```
Comment (bbakerman) [inline src/main/java/graphql/analysis/QueryTraverser.java:73]: This is one for Andi omre yhan you - but since `ValuesResolver` is a stateless class - we should move to static entry points.   Object allocation is cheap - but statics are even cheaper AND it says its a singleton

File: src/main/java/graphql/analysis/QueryTraverser.java [hunk 5]
```diff
@@ -51,32 +51,38 @@ public class QueryTraverser {
...
                            Map<String, FragmentDefinition> fragmentsByName,
-                           Map<String, Object> variables) {
-        this.schema = assertNotNull(schema, () -> "schema can't be null");
-        assertNotNull(root, () -> "root can't be null");
+                           CoercedVariables coercedVariables) {
+        this.schema = schema;
         this.roots = Collections.singleton(root);
-        this.rootParentType = assertNotNull(rootParentType, () -> "rootParentType can't be null");
-        this.fragmentsByName = assertNotNull(fragmentsByName, () -> "fragmentsByName can't be null");
-        this.coercedVariables = new CoercedVariables(assertNotNull(variables, () -> "variables can't be null"));
```
Comment (bbakerman) [inline src/main/java/graphql/analysis/QueryTraverser.java:79]: are the asserts removed because these invariants are no longer true?

File: src/test/groovy/graphql/schema/CoercingTest.groovy [hunk 6]
```diff
@@ -214,4 +216,79 @@ class CoercingTest extends Specification {
...
+        Object parseValue(Object input) throws CoercingParseValueException {
+            return parseDateTimeValue(input)
+        }
+
+        @Override
+        Object parseLiteral(Object input) throws CoercingParseLiteralException {
+            return input
+        }
+    })
+    .build()
```
Comment (bbakerman) [inline src/test/groovy/graphql/schema/CoercingTest.groovy:248]: Nice one - great repo!

**Review by bbakerman — APPROVED** [review]
I am guessing that you have multiple entry points into the constructor and hence the asserts of nbull ness got moved up into the builder

File: src/main/java/graphql/analysis/QueryTraverser.java (hunk 3 above)
Comment (dondonz) [reply src/main/java/graphql/analysis/QueryTraverser.java:55]: You probably saw it later - the null assert is inside the builder now

File: src/main/java/graphql/analysis/QueryTraverser.java (hunk 5 above)
Comment (dondonz) [reply src/main/java/graphql/analysis/QueryTraverser.java:79]: I'm adding 2 new constructors so to keep the code tidier I thought I would move all the null checks into the builder, rather than having to remember 4 lots of asserts

File: src/main/java/graphql/analysis/QueryTraverser.java (hunk 4 above)
Comment (dondonz) [reply src/main/java/graphql/analysis/QueryTraverser.java:73]: That's a good point, doesn't make sense to have an instance here.

I'll have a chat to Andi and make this change in a separate PR
