### PR TITLE
Fix #1440 ClassCastException - fragment with wrong input type condition

### LINKED ISSUE #1440: Using fragments on the input as outputs doesn't fail in parsing
**Describe the bug**

In the following mutation call, we're defining a fragment on the UDIInput input. The fragment is called UDIInputFields and if this is a fragment on the input, it cannot be used as an output. If we use it in the output such as below, query parsing succeeds, however query execution fails with the exception below.

```
mutation UpdateUDI($crd: UserCreds!, $input: UDIInput!) { 
updateUDI(crd: $crd, input: $input) { 
...UDIInputFields 
__typename 
} 
} 

fragment UDIInputFields on UDIInput { 
device
version 
__typename 
} 
```
```
graphql.schema.GraphQLInputObjectType cannot be cast to graphql.schema.GraphQLOutputType
java.lang.ClassCastException: graphql.schema.GraphQLInputObjectType cannot be cast to graphql.schema.GraphQLOutputType
	at graphql.validation.rules.OverlappingFieldsCanBeMerged.collectFieldsForFragmentSpread(OverlappingFieldsCanBeMerged.java:308) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.rules.OverlappingFieldsCanBeMerged.collectFields(OverlappingFieldsCanBeMerged.java:294) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.rules.OverlappingFieldsCanBeMerged.leaveSelectionSet(OverlappingFieldsCanBeMerged.java:58) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.RulesVisitor.leaveSelectionSet(RulesVisitor.java:210) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.RulesVisitor.leave(RulesVisitor.java:197) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:42) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:28) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.validation.Validator.validateDocument(Validator.java:42) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.GraphQL.validate(GraphQL.java:539) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.GraphQL.parseAndValidate(GraphQL.java:509) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.GraphQL.lambda$parseValidateAndExecute$3(GraphQL.java:490) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.get(NoOpPreparsedDocumentProvider.java:11) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:486) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:401) ~[graphql-java-2019-01-10T17-57-42-5caa4f29.jar:?]
--
```
**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.

### PR DESCRIPTION
**Pull request by tinnou**
## Description

In cases where a fragment type condition is invalid (say it was an input type instead of a composite type), the `FragmentsOnCompositeType` rule rightfully collects the validation error. However, the `OverlappingFieldsCanBeMerged` validation rule is wrongly assuming that the type condition is valid and attempts to cast it as a `GraphQLOutputType`, throwing a `ClassCastException` described in issue #1440.

I wrote a test to reproduce the issue:

```java
    def schema = TestUtil.schema("""
            type Query {
                nothing: String
            }
            
            type Mutation {
                updateUDI(input: UDIInput!): UDIOutput
            }
            
            type UDIOutput {
                device: String
                version: String
            }
            
            input UDIInput {
                device: String 
                version: String
            }
        """)

    def graphQL = GraphQL.newGraphQL(schema).build()


    def "#1440 when fragment type condition is input type it should return validation error - not classCastException"() {
        when:
        def executionInput = ExecutionInput.newExecutionInput()
                .query('''                    
                    mutation UpdateUDI($input: UDIInput!) { 
                        updateUDI(input: $input) { 
                            ...fragOnInputType 
                            __typename 
                        } 
                    }
                    
                    # fragment should only target composite types
                    fragment fragOnInputType on UDIInput { 
                        device
                        version 
                        __typename 
                    } 
                    
                    ''')
                .variables([input: [device: 'device', version: 'version'] ])
                .build()

        def executionResult = graphQL.execute(executionInput)

        then:

        executionResult.data == null
        executionResult.errors.size() == 1
        (executionResult.errors[0] as ValidationError).validationErrorType == ValidationErrorType.InlineFragmentTypeConditionInvalid
    }
```
and this throws 
```
graphql.Issue1440 > #1440 when fragment type condition is input type it should return validation error - not classCastException FAILED
    java.lang.ClassCastException: graphql.schema.GraphQLInputObjectType cannot be cast to graphql.schema.GraphQLOutputType
        at graphql.validation.rules.OverlappingFieldsCanBeMerged.collectFieldsForFragmentSpread(OverlappingFieldsCanBeMerged.java:308)
        at graphql.validation.rules.OverlappingFieldsCanBeMerged.collectFields(OverlappingFieldsCanBeMerged.java:294)
        at graphql.validation.rules.OverlappingFieldsCanBeMerged.leaveSelectionSet(OverlappingFieldsCanBeMerged.java:58)
```

## Fix
The fix consists of removing the un-necessary casts as they appear to not be needed. 

I also added an additional test to cover for inline fragments as well. 

I will do a second PR for the stable branch.

### CODE REVIEW

**Comment by tinnou** [comment]
Hmm, looks like there is a flaky test. Have you seen this before? I'm unable to reproduce on my local so far. I'll try further.

```
<==========---> 83% EXECUTING [44s]> :test > 662 tests completed> :test > Executing test ...DataLoaderPerformanceWithChainedInstrumentationTest<==========---> 83% EXECUTING [44s]> :test > 662 tests completed> :test > Executing test ...DataLoaderPerformanceWithChainedInstrumentationTestentation.dataloader.DataLoaderPerformanceWithChainedInstrumentationTest > chainedInstrumentation: 970 ensure data loader is performant for multiple field with lists FAILED
    Condition not satisfied:
    batchCompareDataFetchers.departmentsForShopsBatchLoaderCounter.get() == 1
    |                        |                                     |     |
    |                        2                                     2     false
    graphql.execution.instrumentation.dataloader.BatchCompareDataFetchers@60f76b0
        at graphql.execution.instrumentation.dataloader.DataLoaderPerformanceWithChainedInstrumentationTest.chainedInstrumentation: 970 ensure data loader is performant for multiple field with lists(DataLoaderPerformanceWithChainedInstrumentationTest.groovy:66)

```

**Comment by tinnou** [comment]
I was able to reproduce the issue by running the single method `DataLoaderPerformanceTest.970 ensure data loader is performant for multiple field with lists.`

It looks like the `departmentsForShopsBatchLoader` gets called twice with two sets of 3 shop ids: `ids[shop-1, shop-2, shop-3]` and `ids[exshop-1, exshop-2, exshop-3]`
instead of once with a single set of 6 shop ids: `ids[shop-1, exshop-1, shop-2, exshop-2, exshop-3, shop-3]`.

There is a random sleep in `BatchCompareDataFetchers.sleepSome` which I believe to be the culprit. The shops batch loader are dispatched at the same time, but with this random sleep the shop results might actually be resolved at different times. When configuring the sleep time to be 1ms for the shops and 1000ms for the expensive shops, the issue happens consistently.

My intuition is the random sleep was introduced for the deferred scenarios and is now randomly impacting the non-deferred test case. I can put together a PR to separate these use cases if you think I'm on the right path.

**Comment by andimarek** [comment]
@tinnou thanks a lot for looking into the flaky test. I am not sure if you are on the right path ... will also have a look.

**Comment by andimarek** [comment]
@tinnou you were right: it is very likely caused by theses sleeps combined with the general behaviour of the field level tracking approach. We will fix that test.

**Comment by andimarek** [comment]
@tinnou the test is fixed

File: src/test/groovy/graphql/Issue1440.groovy [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+                .variables([input: [device: 'device', version: 'version'] ])
+                .build()
+
+        def executionResult = graphQL.execute(executionInput)
+
+        then:
+
+        executionResult.data == null
+        executionResult.errors.size() == 1
+        (executionResult.errors[0] as ValidationError).validationErrorType == ValidationErrorType.InlineFragmentTypeConditionInvalid
```
Comment (andimarek) [inline src/test/groovy/graphql/Issue1440.groovy]: this seems wrong or the naming is off: it is not a InlineFragment. 🤔

Comment (tinnou) [reply src/test/groovy/graphql/Issue1440.groovy]: oh great catch. The `FragmentsOnCompositeType` is indeed using the wrong enum value. I would do another PR to fix it but since it's fairly small, I'll fix in this one if that's ok.

Comment (andimarek) [reply src/test/groovy/graphql/Issue1440.groovy]: sure ... do it in one ... thanks

**Comment by andimarek** [comment]
thanks
