### PR TITLE
1847: Fix circular reference between input object field/type

### LINKED ISSUE #1847: Regression in v14.0: stack overflow in some error conditions, shadowing the actual error
**Describe the bug**
This manifests when all those conditions are met:
* an argument whose type has a circular reference (in the repro code below, this is specifically the `not : IDFilter`; the `and : [IDFilter!]` does not seem to trigger the issue)
* the return type is non-null (using `[Entity!]` won't trigger the bug, only `[Entity!]!` will; it needs not be a list though)
* the data fetcher errors out

I bisected it to 2e990d1ecc630da2651ac4dae329947ba2673867 which adds a `toString()` to `GraphQLInputObjectField`.
Here's what seems to happen, from my debugging session: the exception thrown by the data fetcher is handled and added to the list of errors and then execution continues as if the data fetcher returned null (https://github.com/graphql-java/graphql-java/blob/9eae9c1bf506700cd0a54bf37364e28e2519a2f4/src/main/java/graphql/execution/ExecutionStrategy.java#L287-L288). This will later cause a `NonNullableFieldWasNullException`, and when it's passed as a cause to a `CompletionException`, the `Throwable` constructor will call its `toString()`, which will ultimately call `toString()` on the `GraphQLInputObjectField` representing the `filter` argument and/or its `not` field. This will cause an infinite recursion leading to a stack overflow.

Actually, having the data fetcher return null will also trigger the stack overflow, though in this case it would *also* be a bug in the data fetcher for not following the schema contract. Throwing an exception does not violate the contract though!

**To Reproduce**

This repro case is a bit more complex than it needs to be, but closer to my actual use-case:
```groovy
package graphql

import graphql.schema.idl.RuntimeWiring
import spock.lang.Specification

class Regression extends Specification {
    def graphql = TestUtil.graphQL('''
                type Query {
                    list(filter : IDFilter) : [Entity!]!
                }
                type Entity {
                    id : ID!
                }
                input IDFilter {
                    and : [IDFilter!]
                    or : [IDFilter!]
                    not : IDFilter
                    eq : ID,
                    in : [ID!]
                    ne : ID
                    notIn : [ID!]
                }
            ''',
            RuntimeWiring.newRuntimeWiring()
                    .type("Query") {
                        it.dataFetcher("list") {
                            throw new RuntimeException("oops!");
                        }
                    }.build())
            .build()

    def regression() {
        when:
        def input = ExecutionInput.newExecutionInput()
                .query('query { list { id } }')
                .build()
        def executionResult = graphql.execute(input)

        then:
        executionResult.data == null
        executionResult.dataPresent
        executionResult.errors.size() == 1
        executionResult.errors[0].message == "Exception while fetching data (/list) : oops!"
        executionResult.errors[0].path == ["list"]
        executionResult.errors[0] instanceof ExceptionWhileDataFetching
    }
}
```

### PR DESCRIPTION
**Pull request by felipe-gdr**
The source of the problem here is the circular reference created by the `toString` implementations in `GraphQLInputObjectField` and `GraphQLInputObjectType`. 
The stack overflow error will happen every time there's a circular reference between field/type and `toString` is called in one class or the other. This PR tries to fix that.

Fixes #1847

### CODE REVIEW

File: src/main/java/graphql/schema/GraphQLInputObjectField.java [hunk 1]
```diff
@@ -170,14 +170,20 @@ public String toString() {
         return "GraphQLInputObjectField{" +
                 "name='" + name + '\'' +
                 ", description='" + description + '\'' +
-                ", originalType=" + originalType +
+                ", originalType=" + inputTypeToStringAvoidingCircularReference(originalType) +
                 ", defaultValue=" + defaultValue +
                 ", definition=" + definition +
                 ", directives=" + directives +
-                ", replacedType=" + replacedType +
+                ", replacedType=" + inputTypeToStringAvoidingCircularReference(replacedType) +
```
Comment (felipe-gdr) [inline src/main/java/graphql/schema/GraphQLInputObjectField.java:177]: This is a simple mechanism to break the infinite cycle. 
It could be implemented in either class. I've decided to the check in `GraphQLInputObjectField` for no particular reason.

File: src/test/groovy/graphql/Issue1847.groovy [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+import spock.lang.Specification
+
+class Issue1847 extends Specification {
+    def schema = TestUtil.schema('''
+                type Query {
+                    listWithCircularReference(filter : TypeWithCircularReference) : String 
+                    list(filter : Type) : String 
+                }
+                input TypeWithCircularReference {
+                    circularField : Type
```
Comment (tbroyer) [inline src/test/groovy/graphql/Issue1847.groovy:12]: There's no circular reference here

Comment (felipe-gdr) [reply src/test/groovy/graphql/Issue1847.groovy]: You're right @tbroyer , did some last minute refactoring and lost the circular reference here. Just pushed a new commit that fixes it. Cheers!

**Comment by bbakerman** [comment]
@andimarek 

We have been having a few problems (performance and correctness) around our use of `.toString()`

In a tree structure we always run the risk that spidering will cause problems like this or performance problems.

Perhaps we should review our .toStrings and simplfy them to really identifying things like "name"

**Comment by felipe-gdr** [comment]
> @andimarek
> 
> We have been having a few problems (performance and correctness) around our use of `.toString()`
> 
> In a tree structure we always run the risk that spidering will cause problems like this or performance problems.
> 
> Perhaps we should review our .toStrings and simplfy them to really identifying things like "name"

Do you think users might miss the extra info that is current being outputted on `toString` though? While debugging, for instance.

**Comment by tbroyer** [comment]
There might be 2 use cases:

* when working with schemas (not my use case, so don't have an opinion), you might want to have details on your types similar to the current `toString()` (fixed to handle recursive types though, displaying only its name in this case on second encounter)
* when executing requests (my use case, e.g. when including the type in an exception's message), the name of the type (and possibly its kind `scalar`, `enum`, `type` or `input`) should be enough. So changing the `toString()` of the exceptions should be enough here.
